"""Initial migration

Revision ID: 154aee8e5e83
Revises: 012a01953fb9
Create Date: 2025-02-04 11:55:18.693532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154aee8e5e83'
down_revision = '012a01953fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('file_extension', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('file_extension')
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###
